settings:
  prefix: "&e&lStaff &8» &7"
blocked-staffmode: "You &ccan't &7issue this command when staffmode is enabled."
blocked-normal: "You &acan &7only issue this command when staffmode is enabled."

whitelisted-commands: # Commands allowed when in staffmode, anything not listed here will be blocked when SM is enabled.
  - "staffmode"
  - "sm"
  - "modmode"
  - "mod"
  - "freeze"
  - "ss"
  - "inspect"
  - "invsee"
  - "alts"
  - "checkalts"
  - "fakebase"
  - "fakediamonds"
  - "punish"
  - "ban"
  - "kick"
  - "mute"
  - "ipban"
  - "blacklist"
  - "tempban"
  - "clearchat"
  - "lockchat"
  - "slowchat"
  - "vanish"
  - "v"

blacklisted-commands: # Commands blocked when not in staffmode, anything here CAN'T be executed by staff when NOT in SM.
  - "fakebase"
  - "fakediamonds"